// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:2bd98eed-c39e-4283-b2c8-af72b96d4a44",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_b1YwJ3jRS",
    "aws_user_pools_web_client_id": "3f7ipgsj5tjkbpodiput2ehnfh",
    "oauth": {}
};


export default awsmobile;
